### ISSUE TITLE
Add LTV in timestamp signatures

### ISSUE THREAD

**Issue by FreddyKaiser** [SCS-CBU-CED-IAM/setapdfsigner-ais#2]
Timestamped only PDFs are not displaying the "LTV Enabled" details when verified by Adobe Reader. In order to fix this the Revocation Details must be added in the DSS Structure.

**Comment by Setasign** [comment]
Handling for DSS structure will be available in the next official release of the SetaPDF-Signer component. It's already implemented. I would suggest to add a getter to the AIS.php class to allow an easy access to the desired data instead of getting the low level XML result.

**Comment by FreddyKaiser** [comment]
Done within https://github.com/Setasign/SetaPDF-Signer-Addon-SwisscomAIS
